Cinema-World/Controllers/ActorsController.cs
using Cinema_World.Data;
using Cinema_World.Data.Services;
using Cinema_World.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema_World.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allActors = await _service.GetAllAsync();
            return View(allActors);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("FirstName,MiddleName,LastName,BirthYear,BirthPlace")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIDAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIDAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIDAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIDAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Cinema-World/Controllers/CinematographyController.cs
using Cinema_World.Data;
using Cinema_World.Data.Services;
using Cinema_World.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;

namespace Cinema_World.Controllers
{
    public class CinematographyController : Controller
    {

        private readonly ICinematographyService _service;

        public CinematographyController(ICinematographyService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allCinematography = await _service.GetAllAsync(n => n.Genre, d => d.Director, m => m.CinematographyCategories_Cinematography);
            return View(allCinematography);
        }


        public async Task<IActionResult> Filter(string searchString)
        {
            var allCinematography = await _service.GetAllAsync(n => n.Genre, d => d.Director);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allCinematography.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.ShortDescription.ToLower().Contains(searchString.ToLower())).ToList();
                
                if(filteredResult.Count == 0) return View("NotFound");
                
                return View("Index", filteredResult);
            }
            
            return View("Index", allCinematography);
        }

        public async Task<IActionResult> Details(int id)
        {
            var cinematographyDetails = await _service.GetCinematographyByIDAsync(id);
            if (cinematographyDetails == null) return View("NotFound");
            return View(cinematographyDetails);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var cinematographyDropdownData = await _service.GetCinematographyDropdownValues();

            ViewBag.Genres = new SelectList(cinematographyDropdownData.Genres, "ID", "Name");
            ViewBag.Categories = new SelectList(cinematographyDropdownData.Categories, "ID", "Name");
            ViewBag.Actors = new SelectList(cinematographyDropdownData.Actors, "ID", "FullName");
            ViewBag.Writers = new SelectList(cinematographyDropdownData.Writers, "ID", "FullName");
            ViewBag.Directors = new SelectList(cinematographyDropdownData.Directors, "ID", "FullName");

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CinematographyViewModel cinematography)
        {
            if(!ModelState.IsValid)
            {
                var cinematographyDropdownData = await _service.GetCinematographyDropdownValues();

                ViewBag.Genres = new SelectList(cinematographyDropdownData.Genres, "ID", "Name");
                ViewBag.Categories = new SelectList(cinematographyDropdownData.Categories, "ID", "Name");
                ViewBag.Actors = new SelectList(cinematographyDropdownData.Actors, "ID", "FullName");
                ViewBag.Writers = new SelectList(cinematographyDropdownData.Writers, "ID", "FullName");
                ViewBag.Directors = new SelectList(cinematographyDropdownData.Directors, "ID", "FullName");

                return View(cinematography);
            }
            await _service.AddNewCinematographyAsync(cinematography);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var cinematographyDetails = await _service.GetCinematographyByIDAsync(id);
            if (cinematographyDetails == null) return View("NotFound");

            var response = new CinematographyViewModel()
            {
                ID = cinematographyDetails.ID,
                Name = cinematographyDetails.Name,
                Picture = cinematographyDetails.Picture,
                ShortDescription = cinematographyDetails.ShortDescription,
                ReleaseYear = cinematographyDetails.ReleaseYear,
                IMDbScore = cinematographyDetails.IMDbScore,
                DirectorID = cinematographyDetails.DirectorID,
                GenreID = cinematographyDetails.GenreID,
                ActorIDs = cinematographyDetails.Actors_Cinematography.Select(a => a.ActorID).ToList(),
                WriterIDs = cinematographyDetails.Writers_Cinematography.Select(w => w.WriterID).ToList(),
                CinematographyCategoryIDs = cinematographyDetails.CinematographyCategories_Cinematography.Select(c => c.CinematographyCategoryID).ToList(),
            };

            var cinematographyDropdownData = await _service.GetCinematographyDropdownValues();

            ViewBag.Genres = new SelectList(cinematographyDropdownData.Genres, "ID", "Name");
            ViewBag.Categories = new SelectList(cinematographyDropdownData.Categories, "ID", "Name");
            ViewBag.Actors = new SelectList(cinematographyDropdownData.Actors, "ID", "FullName");
            ViewBag.Writers = new SelectList(cinematographyDropdownData.Writers, "ID", "FullName");
            ViewBag.Directors = new SelectList(cinematographyDropdownData.Directors, "ID", "FullName");

            return View(response);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, CinematographyViewModel cinematography)
        {
            if (id != cinematography.ID) return View("NotFound");


            if (!ModelState.IsValid)
            {
                var cinematographyDropdownData = await _service.GetCinematographyDropdownValues();

                ViewBag.Genres = new SelectList(cinematographyDropdownData.Genres, "ID", "Name");
                ViewBag.Categories = new SelectList(cinematographyDropdownData.Categories, "ID", "Name");
                ViewBag.Actors = new SelectList(cinematographyDropdownData.Actors, "ID", "FullName");
                ViewBag.Writers = new SelectList(cinematographyDropdownData.Writers, "ID", "FullName");
                ViewBag.Directors = new SelectList(cinematographyDropdownData.Directors, "ID", "FullName");

                return View(cinematography);
            }
            await _service.UpdateCinematographyAsync(cinematography);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var cinematographyDetails = await _service.GetCinematographyByIDAsync(id);
            if (cinematographyDetails == null) return View("NotFound");
            return View(cinematographyDetails);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinematographyDetails = await _service.GetCinematographyByIDAsync(id);
            if (cinematographyDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Cinema-World/Controllers/DirectorsController.cs
using Cinema_World.Data;
using Cinema_World.Data.Services;
using Cinema_World.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema_World.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly IDirectorsService _service;

        public DirectorsController(IDirectorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allDirectors = await _service.GetAllAsync();
            return View(allDirectors);
        }

        public async Task<IActionResult> Details(int id)
        {
            var directorDetails = await _service.GetByIDAsync(id);
            if (directorDetails == null) return View("NotFound");
            return View(directorDetails);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("FirstName,MiddleName,LastName,BirthYear,BirthPlace")] DirectorModel director)
        {
            if (!ModelState.IsValid)
            {
                return View(director);
            }
            await _service.AddAsync(director);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var directorDetails = await _service.GetByIDAsync(id);
            if (directorDetails == null) return View("NotFound");
            return View(directorDetails);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, DirectorModel director)
        {
            if (!ModelState.IsValid)
            {
                return View(director);
            }
            await _service.UpdateAsync(id, director);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var directorDetails = await _service.GetByIDAsync(id);
            if (directorDetails == null) return View("NotFound");
            return View(directorDetails);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var directorDetails = await _service.GetByIDAsync(id);
            if (directorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Cinema-World/Controllers/WritersController.cs
using Cinema_World.Data;
using Cinema_World.Data.Services;
using Cinema_World.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema_World.Controllers
{
    public class WritersController : Controller
    {
        private readonly IWritersService _service;

        public WritersController(IWritersService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allWriters = await _service.GetAllAsync();
            return View(allWriters);
        }

        public async Task<IActionResult> Details(int id)
        {
            var writerDetails = await _service.GetByIDAsync(id);
            if (writerDetails == null) return View("NotFound");
            return View(writerDetails);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("FirstName,MiddleName,LastName,BirthYear,BirthPlace")] WriterModel writer)
        {
            if (!ModelState.IsValid)
            {
                return View(writer);
            }
            await _service.AddAsync(writer);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var writerDetails = await _service.GetByIDAsync(id);
            if (writerDetails == null) return View("NotFound");
            return View(writerDetails);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, WriterModel writer)
        {
            if (!ModelState.IsValid)
            {
                return View(writer);
            }
            await _service.UpdateAsync(id, writer);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var writerDetails = await _service.GetByIDAsync(id);
            if (writerDetails == null) return View("NotFound");
            return View(writerDetails);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var writerDetails = await _service.GetByIDAsync(id);
            if (writerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Cinema-World/Views/Shared/NotFound.cshtml
@*Define ViewData*@

@{
    ViewData["Title"] = "Error";
}

@*Write code*@
<div class="row text-center">
    <h1>Something went wrong...</h1>
    <hr />
    <h2>Please, try again or return home</h2>
    <a class="link-info fs-5" asp-controller="Home" asp-action="Index">Return home</a>
</div>

Cinema-World/Views/Shared/_CreatePartial.cshtml
@model string;

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="text-white pe-5 pb-5 fixed-bottom">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success float-end">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Cinema-World/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if(!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0 me-3" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log In
    </a>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-badge"></i> Register
    </a>
} else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" id="profile-btn" aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="Profile" asp-route-id="@UserManager.GetUserId(User)">
                    <i class="bi bi-person-circle"></i> Profile
                </a>
            </li>

            @if(User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
            
        </ul>
    </div>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0 ms-2">
            <i class="bi bi-door-open"></i> Logout
        </button>
    </form>
}

Cinema-World/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema World!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cinema_World.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" sizes="16x16" href="@Url.Content("~/favicon/favicon.ico")">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema World</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><i class="bi bi-camera-reels"></i> About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts"><i class="bi bi-telephone-inbound"></i> Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cinematography" asp-action="Index"> <i class="badge-info bi-film"></i> Cinematography</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Favorites" asp-action="MyFavorites"> <i class="bi bi-star-fill"></i> Favorites</a>
                        </li>

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Manage
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Directors" asp-action="Index"><i class="bi bi-mortarboard"></i> Directors</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-rolodex"></i> Actors</a>
                                    <a class="dropdown-item" asp-controller="Writers" asp-action="Index"><i class="bi bi-vector-pen"></i> Writers</a>
                                </div>
                            </li>
                        }

                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-shield-check"></i> Privacy</a>
                        </li>
                    </ul>

                    <form class="d-flex form-inline my-2 my-lg-0 pe-3" asp-controller="Cinematography" asp-action="Filter">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Search for a movie" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>